const categorySeedData = [
    { name: "Tim mạch", slug: "tim-mach", categoryKind: "medicine", sortOrder: 1, description: "Thuốc hỗ trợ tim mạch, huyết áp." },
    { name: "Tiêu hóa", slug: "tieu-hoa", categoryKind: "medicine", sortOrder: 2, description: "Thuốc dạ dày, đại tràng, gan mật." },
    { name: "Vitamin & Khoáng chất", slug: "vitamin-khoang-chat", categoryKind: "supplement", sortOrder: 3, description: "Bổ sung vitamin và khoáng chất." },
    { name: "TPCN", slug: "tpcn", categoryKind: "supplement", sortOrder: 4, description: "Thực phẩm bảo vệ sức khỏe." },
    { name: "Thiết bị y tế", slug: "thiet-bi-y-te", categoryKind: "device", sortOrder: 5, description: "Máy đo, nhiệt kế, dụng cụ y tế." },
    { name: "Mẹ và bé", slug: "me-va-be", categoryKind: "personal_care", sortOrder: 6, description: "Sản phẩm cho mẹ và trẻ nhỏ." },
    { name: "Da - Tóc - Móng", slug: "da-toc-mong", categoryKind: "cosmetic", sortOrder: 7, description: "Dược mỹ phẩm, chăm sóc da." }
];

const brandSeedData = [
    { name: "DHG Pharma", slug: "dhg-pharma", country: "Việt Nam", logo: "https://picsum.photos/seed/dhg/120/120" },
    { name: "Sanofi", slug: "sanofi", country: "Pháp", logo: "https://picsum.photos/seed/sanofi/120/120" },
    { name: "OPC", slug: "opc", country: "Việt Nam", logo: "https://picsum.photos/seed/opc/120/120" },
    { name: "Omron", slug: "omron", country: "Nhật Bản", logo: "https://picsum.photos/seed/omron/120/120" },
    { name: "Blackmores", slug: "blackmores", country: "Úc", logo: "https://picsum.photos/seed/blackmores/120/120" }
];

const productSeedData = [
    {
        sku: "MED-OTC-001",
        name: "Paracetamol 500mg OPC",
        shortDescription: "Giảm đau, hạ sốt",
        description: "Thuốc giảm đau, hạ sốt cho người lớn và trẻ em trên 12 tuổi.",
        price: 28000,
        salePrice: 25000,
        images: ["https://picsum.photos/seed/med-paracetamol/800/600"],
        stock: 200,
        sold: 540,
        categorySlug: "tieu-hoa",
        brandSlug: "opc",
        productType: "medicine_otc",
        unitLabel: "Vỉ",
        packagingDescription: "Vỉ 10 viên",
        isNew: false,
        isBestSeller: true,
        isSale: true,
        medicineDetail: {
            activeIngredient: "Paracetamol 500mg",
            registrationNo: "VD-12345-18",
            dosageForm: "tablet",
            concentration: "500mg",
            indications: "Giảm đau, hạ sốt",
            usage: "Người lớn: 1-2 viên/lần, tối đa 8 viên/ngày",
            warnings: "Không dùng quá liều. Thận trọng bệnh gan.",
            storage: "Nơi khô ráo, dưới 30°C"
        },
        batch: { batchCode: "LOT-PARA-01", expiryDate: "2027-12-31", quantity: 200 }
    },
    {
        sku: "MED-OTC-002",
        name: "Oresol điện giải",
        shortDescription: "Bù nước, điện giải khi tiêu chảy",
        description: "Dung dịch uống bù nước và điện giải.",
        price: 12000,
        salePrice: null,
        images: ["https://picsum.photos/seed/med-oresol/800/600"],
        stock: 150,
        sold: 320,
        categorySlug: "tieu-hoa",
        brandSlug: "opc",
        productType: "medicine_otc",
        unitLabel: "Gói",
        packagingDescription: "Hộp 6 gói",
        isBestSeller: true,
        medicineDetail: {
            activeIngredient: "Glucose, Natri clorid, Kali clorid",
            dosageForm: "powder",
            indications: "Tiêu chảy, mất nước",
            usage: "Pha 1 gói với 200ml nước, uống từng ngụm",
            storage: "Nơi khô ráo"
        },
        batch: { batchCode: "LOT-ORE-01", expiryDate: "2028-06-30", quantity: 150 }
    },
    {
        sku: "MED-OTC-003",
        name: "Vitamin C 1000mg",
        shortDescription: "Bổ sung vitamin C",
        description: "Hỗ trợ tăng sức đề kháng.",
        price: 89000,
        salePrice: 79000,
        images: ["https://picsum.photos/seed/med-vitc/800/600"],
        stock: 80,
        sold: 210,
        categorySlug: "vitamin-khoang-chat",
        brandSlug: "blackmores",
        productType: "functional_food",
        unitLabel: "Hộp",
        packagingDescription: "Hộp 30 viên",
        isSale: true,
        medicineDetail: {
            activeIngredient: "Ascorbic acid 1000mg",
            dosageForm: "tablet",
            indications: "Bổ sung vitamin C",
            usage: "1 viên/ngày sau bữa ăn",
            warnings: "Không thay thế thuốc chữa bệnh"
        },
        batch: { batchCode: "LOT-VITC-01", expiryDate: "2027-09-30", quantity: 80 }
    },
    {
        sku: "MED-RX-001",
        name: "Amlodipine 5mg (tham khảo)",
        shortDescription: "Thuốc tim mạch kê đơn",
        description: "Thuốc điều trị tăng huyết áp theo chỉ định bác sĩ.",
        price: 45000,
        salePrice: null,
        images: ["https://picsum.photos/seed/med-amlodipine/800/600"],
        stock: 40,
        sold: 88,
        categorySlug: "tim-mach",
        brandSlug: "sanofi",
        productType: "medicine_rx",
        unitLabel: "Hộp",
        packagingDescription: "Hộp 3 vỉ x 10 viên",
        requiresPharmacistAdvice: true,
        medicineDetail: {
            activeIngredient: "Amlodipine 5mg",
            dosageForm: "tablet",
            prescriptionRequired: true,
            indications: "Tăng huyết áp",
            usage: "Theo đơn bác sĩ",
            warnings: "Thuốc kê đơn - chỉ dùng khi có chỉ định"
        },
        batch: { batchCode: "LOT-AML-01", expiryDate: "2027-03-31", quantity: 40 }
    },
    {
        sku: "MED-DEV-001",
        name: "Máy đo huyết áp Omron",
        shortDescription: "Đo huyết áp tại nhà",
        description: "Máy đo huyết áp tự động cánh tay.",
        price: 1290000,
        salePrice: 1150000,
        images: ["https://picsum.photos/seed/med-omron-bp/800/600"],
        stock: 25,
        sold: 67,
        categorySlug: "thiet-bi-y-te",
        brandSlug: "omron",
        productType: "medical_device",
        unitLabel: "Bộ",
        packagingDescription: "1 máy + cuff",
        isNew: true,
        isSale: true,
        batch: { batchCode: "LOT-OMRON-01", expiryDate: "2030-01-01", quantity: 25 }
    },
    {
        sku: "MED-DEV-002",
        name: "Nhiệt kế điện tử",
        shortDescription: "Đo nhiệt độ nhanh",
        description: "Nhiệt kế điện tử đầu mềm cho trẻ em và người lớn.",
        price: 185000,
        salePrice: null,
        images: ["https://picsum.photos/seed/med-thermometer/800/600"],
        stock: 60,
        sold: 145,
        categorySlug: "thiet-bi-y-te",
        brandSlug: "omron",
        productType: "medical_device",
        unitLabel: "Cái",
        isBestSeller: true,
        batch: { batchCode: "LOT-TEMP-01", expiryDate: "2029-12-31", quantity: 60 }
    },
    {
        sku: "MED-TPCN-001",
        name: "Omega-3 Fish Oil",
        shortDescription: "Dầu cá hỗ trợ tim mạch",
        description: "TPCN bổ sung omega-3.",
        price: 320000,
        salePrice: 289000,
        images: ["https://picsum.photos/seed/med-omega3/800/600"],
        stock: 45,
        sold: 98,
        categorySlug: "tpcn",
        brandSlug: "blackmores",
        productType: "functional_food",
        unitLabel: "Hộp",
        packagingDescription: "Hộp 60 viên",
        isSale: true,
        medicineDetail: {
            activeIngredient: "Fish oil 1000mg",
            indications: "Hỗ trợ tim mạch, não bộ",
            warnings: "Không phải thuốc thay thế điều trị"
        },
        batch: { batchCode: "LOT-OM3-01", expiryDate: "2027-11-30", quantity: 45 }
    },
    {
        sku: "MED-COS-001",
        name: "Kem dưỡng da B5",
        shortDescription: "Phục hồi da kích ứng",
        description: "Kem dưỡng hỗ trợ phục hồi da sau treatment.",
        price: 165000,
        salePrice: 149000,
        images: ["https://picsum.photos/seed/med-b5/800/600"],
        stock: 70,
        sold: 132,
        categorySlug: "da-toc-mong",
        brandSlug: "dhg-pharma",
        productType: "cosmetic",
        unitLabel: "Tuýp",
        packagingDescription: "Tuýp 30g",
        isSale: true,
        batch: { batchCode: "LOT-B5-01", expiryDate: "2028-02-28", quantity: 70 }
    },
    {
        sku: "MED-BABY-001",
        name: "Sữa rửa cho bé",
        shortDescription: "Dịu nhẹ cho da trẻ",
        description: "Sữa tắm gội toàn thân cho trẻ sơ sinh.",
        price: 125000,
        salePrice: null,
        images: ["https://picsum.photos/seed/med-baby-wash/800/600"],
        stock: 55,
        sold: 76,
        categorySlug: "me-va-be",
        brandSlug: "dhg-pharma",
        productType: "personal_care",
        unitLabel: "Chai",
        packagingDescription: "Chai 500ml",
        isNew: true,
        batch: { batchCode: "LOT-BABY-01", expiryDate: "2028-08-31", quantity: 55 }
    },
    {
        sku: "MED-OTC-004",
        name: "Thuốc ho Atussin",
        shortDescription: "Giảm ho, long đờm",
        description: "Hỗ trợ giảm ho do cảm lạnh.",
        price: 42000,
        salePrice: 38000,
        images: ["https://picsum.photos/seed/med-cough/800/600"],
        stock: 0,
        sold: 189,
        categorySlug: "tieu-hoa",
        brandSlug: "dhg-pharma",
        productType: "medicine_otc",
        unitLabel: "Chai",
        packagingDescription: "Chai 100ml",
        isSale: true,
        medicineDetail: {
            activeIngredient: "Dextromethorphan, Guaifenesin",
            dosageForm: "syrup",
            indications: "Ho, long đờm",
            usage: "Theo hướng dẫn trên nhãn"
        }
    }
];

module.exports = {
    categorySeedData,
    brandSeedData,
    productSeedData
};
